name: Changelog

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate Changelog
      uses: orhun/git-cliff-action@v3
      id: git-cliff
      with:
        config: .github/cliff.toml
        args: --verbose
      env:
        OUTPUT: CHANGELOG.md

    - name: Print Changelog
      run: cat "${{ steps.git-cliff.outputs.changelog }}"

    - name: Commit and Push Changes
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add CHANGELOG.md
        git diff --staged --quiet || git commit -m "chore: update changelog [skip ci]"
        git push